# Sweetspot daemon configuration

# inner interface 
inner-interface eth0
inner-gw-mac 86:33:89:28:7c:08

# outer interface 
outer-interface eth1
outer-gw-mac 14:ab:c5:e9:6a:dd


# user IP CIDR (addresses anyhow assigned to user computers)
#user-networks 127.0.0.0
user-networks 10.0.0.1/24 

# SNAT public networks
snat-public-networks 14.0.0.1/32

# authentication server address
uam-server-address 127.0.0.1

# authentication server port
uam-server-port 3993

# authentication server shared secret (auth client must have the same)
uam-secret 1234567890

# report UAM errors back to client (obsolete)
#uam-report-errors 1

# Detail file accounting
acct-detail-file /var/sweetspot/detail

# Interim accounting interval (in secs)
acct-interim-interval 300

# NAS-IP-Address to report in acct detail file
#acct-nas-ip-address 127.0.0.1

# Packet filters directory
filter-dir /home/grigory/sweetspot_cpp/filters/filters

# Captive filter
filter-anonymous default

# Filter reload interval (in secs)
#filter-reload-interval 3600 

#quantity of outer-inner threads (thread_qnty mod 2 should be 0) 
thread_qnty 4  

local-networks 18.0.0.2/32

